import '@/app/globals.css'
import { Inter } from 'next/font/google'
import {ReduxStoreProvider} from "@/Redux/ReduxStoreProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Next Pocketbase Auth',
	description: 'Generated by create next app',
}

export default function RootLayout({
	                                   children,
                                   }: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
		<body className={inter.className}>
			<ReduxStoreProvider>{children}</ReduxStoreProvider>
		</body>
		</html>
	)
}
